<?php
session_start();
require('header.php') 
?>      
        <div class="main">
        
            <p class="tos">
            <a href="http://www.upload-fast.com">Upload-Fast.com </a>does not knowingly host any unlawful, harmful, threatening, abusive, illegal, copyright infringing, harassing, tortuous, defamatory, vulgar, obscene, libelous, invasive of another's privacy, hateful, or racially, ethnically or otherwise objectionable; harm minors in any way; impersonate any person or entity, content. We take strong action against piracy and do not tolerate it.
            </p>
            
            <p class="tos">
            YOU AGREE TO NOT UPLOAD ANY UNLAWFUL, HARMFUL, THREATENING, ABUSIVE, ILLEGAL, COPYRIGHT INFRINGING, HARASSING, TORTUOUS, DEFAMATORY, VULGAR, OBSCENE, LIBELOUS, INVASIVE OF ANOTHER'S PRIVACY, HATEFUL, OR RACIALLY, ETHNICALLY OR OTHERWISE OBJECTIONABLE; HARM MINORS IN ANY WAY; IMPERSONATE ANY PERSON OR ENTITY, CONTENT.</p>
        
              <h1>DISCLAIMER</h1>
                <p class="tos">
                    THE WEBSITES' SERVICE IS PROVIDED "AS IS" AND YOU USE IT AT YOUR SOLE RISK. <a href="http://www.upload-fast.com">Upload-Fast.com </a>EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT.

WITHOUT LIMITATION, <a href="http://www.upload-fast.com">Upload-Fast.com </a> MAKES NO WARRANTY THAT THE WEBSITES' SERVICE WILL MEET YOUR REQUIREMENTS, THAT IT WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE, THAT THE RESULTS OBTAINED FROM THE USE OF THE WEBSITES' SERVICE WILL BE ACCURATE OR RELIABLE, OR THAT THE QUALITY OF ANY PRODUCTS, SERVICES, INFORMATION, OR OTHER MATERIAL OBTAINED THROUGH THE WEBSITES' SERVICE WILL MEET YOUR EXPECTATIONS.

ANY MATERIAL DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE WEBSITES' SERVICE IS DONE AT YOUR SOLE RISK AND YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF ANY SUCH MATERIAL. 
                </p>
            
             <h1>LIMITATION OF LIABILITY</h1>
                <p class="tos">
                     YOU EXPRESSLY UNDERSTAND AND AGREE THAT <a href="http://www.upload-fast.com">Upload-Fast.com </a>SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES, INCLUDING BUT NOT LIMITED TO, DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA OR OTHER INTANGIBLE LOSSES (EVEN IF <a href="http://www.upload-fast.com">Upload-Fast.com </a>HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES), RESULTING FROM: (i) THE USE OR THE INABILITY TO USE THE HOSTING SERVICE; (ii) THE COST OF PROCUREMENT OF SUBSTITUTE GOODS AND SERVICES RESULTING FROM ANY GOODS, DATA, INFORMATION OR SERVICES PURCHASED OR OBTAINED OR MESSAGES RECEIVED OR TRANSACTIONS ENTERED INTO THROUGH OR FROM THE WEBSITES' SERVICES; (iii) UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR TRANSMISSIONS OR DATA; (iv) STATEMENTS OR CONDUCT OF ANY THIRD PARTY ON THE WEBSITES' SERVICE; OR (v) ANY OTHER MATTER RELATING TO THE WEBSITES' SERVICE. IN NO EVENT SHALL <a href="http://www.upload-fast.com">Upload-Fast.com</a>'s TOTAL LIABILITY TO YOU FOR ALL DAMAGES, LOSSES, AND CAUSES OF ACTION (WHETHER IN CONTRACT, TORT (INCLUDING, BUT NOT LIMITED TO, NEGLIGENCE), OR OTHERWISE EXCEED THE AMOUNT PAID BY YOU, IF ANY, FOR ACCESSING THIS SITE.

SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF CERTAIN WARRANTIES OR THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES. ACCORDINGLY, SOME OF THE ABOVE LIMITATIONS MAY NOT APPLY TO YOU.              </p>
            <h1>INDEMNIFICATION</h1>
                <p class="tos">
                    YOU ARE ENTIRELY RESPONSIBLE FOR MAINTAINING THE CONFIDENTIALITY OF YOUR PASSWORD AND ACCOUNT. FURTHERMORE, YOU ARE ENTIRELY RESPONSIBLE FOR ANY AND ALL ACTIVITIES WHICH OCCUR UNDER YOUR IP. YOU AGREE TO INDEMNIFY, DEFEND AND HOLD HARMLESS <a href="http://www.upload-fast.com">Upload-Fast.com </a>AND ITS OFFICERS, DIRECTORS, EMPLOYEES, CONSULTANTS AND AGENTS FROM ANY AND ALL THIRD PARTY CLAIMS, LIABILITY, DAMAGES AND/OR COSTS (INCLUDING, BUT NOT LIMITED TO, ATTORNEYS FEES) ARISING FROM YOUR USE OF THE WEBSITES' SERVICE, YOUR VIOLATION OF THE TERMS OF USE OR YOUR INFRINGEMENT, OR INFRINGEMENT BY ANY OTHER USER OF YOUR ACCOUNT, OF ANY INTELLECTUAL PROPERTY OR OTHER RIGHT OF ANY PERSON OR ENTITY. YOU AGREE TO IMMEDIATELY NOTIFY <a href="http://www.upload-fast.com">Upload-Fast.com </a>OF ANY UNAUTHORIZED USE OF YOUR IP OR ANY OTHER BREACH OF SECURITY KNOWN TO YOU.</p>
            <h1>OTHER</h1>
                <p class="tos">
                    BY UPLOADING ANY FILE WITH ANY EXTENSION, YOU AGREE THAT <a href="http://www.upload-fast.com">Upload-Fast.com </a>MAY REMOVE, DELETE, HENCE TO HOST, SERVE, MAKE AVAILABLE, YOUR FILE(S). YOU ALSO AGREE THAT <a href="http://www.upload-fast.com">Upload-Fast.com </a>DOES NOT HAVE TO SUPPLY ANY REASON TO YOU OR ANYONE ELSE AS TO WHY YOUR FILE(S) WERE REMOVED. WE RESERVE THE RIGHT TO DELETE ANY FILE, AT ANY TIME, FOR ANY REASON. "UNLIMITED DOWNLOADS" REFERS TO OUR PROCESSOR AND BANDWIDTH LIMITS. WE MAKE NECESSARY UPGRADES FROM TIME TO TIME, BUT ON SOME OCCASIONS YOUR FILES MAY BE REMOVED DUE TO EXCESSIVE BANDWIDTH, EXCESSIVE CPU. WE ARE NOT BILLIONAIRES WITH UNLIMITED RESOURCES. ALL FILES, SPEED, ETC, ARE HOSTED ON A "BEST EFFORT" BASIS. WE DO NOT MAKE ANY GUARANTEES, WHETHER EXPRESS OR IMPLIED. YOU MAY NOT RESALE YOUR ACCESS TO <a href="http://www.upload-fast.com">Upload-Fast.com</a>. <a href="http://www.upload-fast.com">Upload-Fast.com </a>ALSO RESERVES THE RIGHT TO CHANGE, MODIFY, OR ADD TO THIS (TERMS OF SERVICE) WITHOUT ANY NOTIFICATION TO ANYONE. PLEASE CHECK THIS REGULARLY. <a href="http://www.upload-fast.com">Upload-Fast.com </a>IS NOT RESPONSIBLE FOR ANY CONTENT UPLOADED.
    </div>  
        <p class="footer">&copy; 2007 <a href="http://www.upload-fast.com">Upload-Fast.com</a> - Fast Image Uploads | All Rights Reserved</p>
    </div>
    <b class="rnd_bottom"><b class="rnd_b4"></b><b class="rnd_b3"></b><b class="rnd_b2"></b><b class="rnd_b1"></b></b>
</div>

</body>
</html>
